server:
  port: 8084
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: userTransactions
  application:
    name: userTransactionService
paypal:
  mode: sandbox
  client:
    id: "AcFxM4s-ajIUTPv04DAmjtF2DFM0ISHZhRdQBzGaUjbdRaY6vRO-oqimrPTEXffCKe2VML5KZUkAX0yF"
    secret: "ECSAa34KuItBI3ce6DG7qQFsLe_g0F4MBQa8qQf06a1ZovKY5hrTX7z7dcHecvcyt4pSgyA0Zlm2hSv_"