spring:
  application:
    name: userServiceApp
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: SwapSellUser
server:
  port: 8082
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka