spring:
  mail:
    default-encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: swapsellteam@gmail.com
    password: uewaxvidehmxlbzu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

mail:
  smtp:
    debug: true
server:
  port: 8086
